"""updating db

Revision ID: 3a482342e261
Revises: 5bb4b7bfb04a
Create Date: 2023-11-25 19:06:14.534098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a482342e261'
down_revision = '5bb4b7bfb04a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('input', sa.String(length=530), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('input', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_input_input'), ['input'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('input', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_input_input'))

    op.drop_table('input')
    # ### end Alembic commands ###
